// catflix-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <catflix-modal
      *ngFor='let modal of modals; let i = index;'
      [attr.url]="'https://www.youtube.com/embed/' + modal.id + '?rel=0'"
      [attr.open]='modal.open'
      (modalClose)="modalClose(i)"></catflix-modal>

    <div class="container flex">
      <div class="logo">
        <catflix-logo></catflix-logo>
      </div>
      <div class="cta">
        <catflix-cta text="Who's watching?"></catflix-cta>
      </div>
      <div class="profiles">
          <catflix-profile-thumb
            *ngFor="let profile of profiles; let i = index"
            [attr.img]="'/assets/imgs/' + profile.img"
            [name]="profile.name"
            (click)='viewVideo(i)'></catflix-profile-thumb>
      </div>
      <div class="manage">
        <catflix-button>Manage profiles</catflix-button>
      </div>
    </div>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  modals = [
    {
      id: 'TWDb2Zb6jLQ',
      open: null
    },
    {
      id: 'mSBKZPNsK74',
      open: null
    },
    {
      id: '0Bmhjf0rKe8',
      open: null
    },
    {
      id: 'QH2-TGUlwu4',
      open: null
    }
  ];
  profiles = [
    { img: 'cat-2.jpg', name: 'Cee cee'},
    { img: 'cat-3.jpg', name: 'Cupcake'},
    { img: 'cat-6.jpg', name: 'Tweet tweet'},
    { img: 'cat-7.png', name: 'Garfield'}
  ];

  public viewVideo(index) {
    this.modals[index].open = true;
  }

  public modalClose(index) {
    this.modals[index].open = false;
  }
}

<catflix-modal
    *ngFor='let modal of modals'
    [attr.url]="'https://www.youtube.com/embed/' + modal.id + '?rel=0'"
    [attr.open]='modal.open'></catflix-modal>

<div class="container flex">
    <div class="logo">
        <catflix-logo></catflix-logo>
    </div>
    <div class="cta">
        <catflix-cta text="Who's watching?"></catflix-cta>
    </div>
    <div class="profiles">
        <catflix-profile-thumb
            *ngFor="let profile of profiles; let i = index"
            [attr.img]="'/assets/imgs/' + profile.img"
            [name]="profile.name"
            (click)='viewVideo(i)'></catflix-profile-thumb>
    </div>
    <div class="manage">
        <catflix-button>Manage profiles</catflix-button>
    </div>
</div>

// catflix-react/src/App.js
import React, { Component } from 'react';
import './App.css';
import CatflixModal from './CatflixModal';

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      modals: [
        {
          id: 'TWDb2Zb6jLQ',
          open: null
        },
        {
          id: 'mSBKZPNsK74',
          open: null
        },
        {
          id: '0Bmhjf0rKe8',
          open: null
        },
        {
          id: 'QH2-TGUlwu4',
          open: null
        }
      ],
      profiles: [
        { img: 'netflix-avatar-1.png', name: 'Tim'},
        { img: 'netflix-avatar-2.png', name: 'Cindy'},
        { img: 'netflix-avatar-3.png', name: 'Mum'},
        { img: 'netflix-avatar-4.png', name: 'Grandpa'}
      ]
    };
  }

  render() {
    return (
      <div className="container flex">
        {
          this.state.modals.map((modal, index) => (
            <CatflixModal
              key={ modal.id }
              url={ 'https://www.youtube.com/embed/' + modal.id + '?rel=0' }
              open={ modal.open }
              onModalClose={() => this.modalClose(index) }></CatflixModal>
          ))
        }
        <div className="logo">
          <catflix-logo img='netflix-logo.png'></catflix-logo>
        </div>
        <div className="cta">
          <catflix-cta text="Who's watching?"></catflix-cta>
        </div>
        <div className="profiles">
          {
            this.state.profiles.map((profile, index) => (
              <catflix-profile-thumb
                key={ profile.img }
                img={ profile.img }
                name={ profile.name }
                onClick={ () => { this.viewVideo(index); } }></catflix-profile-thumb>
            ))
          }
        </div>
        <div className="manage">
          <catflix-button>Manage profiles</catflix-button>
        </div>
      </div>
    );
  }

  viewVideo(index) {
    const newModals = [...this.state.modals];
    newModals[index].open = true;
    this.setState({
      modals: newModals
    });
  }

  modalClose(index) {
    const newModals = [...this.state.modals];
    newModals[index].open = false;
    this.setState({
      modals: newModals
    });
  }
}

export default App;
